---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: simple-service
  name: simple-service
  namespace: {{ .Values.app.namespace }}
spec:
  ports:
  - name: 3000-3000
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: simple-busybox
  type: ClusterIP
