---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: simple-pod
  name: simple-pod
  namespace: local
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    args: ["sleep 3000"]
    image: alpine
    name: simple-pod
