---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: simple-pod
  name: simple-pod
  namespace: local
spec:
  ports:
  - port: 4000
    protocol: TCP
    targetPort: 4000
  selector:
    run: simple-pod
