---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: simple-pod
  name: simple-pod
  namespace: local
spec:
  containers:
  - command: ["/bin/sh"] 
    args: ["-c", "sleep 2 && echo done"]
    image: busybox
    name: simple-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
