apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: simple-deploy
  name: simple-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-deploy
  template:
    metadata:
      labels:
        app: simple-deploy
    spec:
      containers:
      - image: nginx:mainline
        name: nginx
