apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: simple-deploy
  name: simple-deploy
  namespace: {{ .Values.app.namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-deploy
  template:
    metadata:
      labels:
        app: simple-deploy
    spec:
      containers:
      - name: {{ .Values.app.deployment.backend.name}}
        image: {{ .Values.app.deployment.backend.image}}:{{ .Values.app.deployment.backend.tag}}
        volumeMounts:
          - name: secret
            mountPath: /secret
        envFrom:
        - secretRef:
            name: simple-secret
              
      volumes:
      - name: secret
        secret:
          secretName: simple-secret

