---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: app-api
  name: app-api
  namespace: {{ .Values.app.namespace }}
spec:
  containers:
  - image: {{ .Values.app.deployment.backend.image }}:red
    name: app-api
