---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: simple-nodeport
    env: local
  name: simple-nodeport
  namespace: {{ .Values.app.namespace }}
spec:
  ports:
  - name: tcp-port
    port: 4000
    protocol: TCP
    targetPort: 4000
    nodePort: 30000
  selector:
    app: app-api
  type: NodePort
