apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-role-binding
  namespace: {{ .Values.app.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-access-role
subjects:
- kind: ServiceAccount
  name: pod-lister
  namespace: {{ .Values.app.namespace }}
