apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pink-deploy
  name: pink-deploy
  namespace: {{ .Values.app.namespace }}
spec:
  replicas: {{ .Values.app.deployment.replicas }}
  selector:
    matchLabels:
      app: pink-deploy
  template:
    metadata:
      labels:
        app: pink-deploy
    spec:
      containers:
      - name: {{ .Values.app.deployment.backend.name}}
        image: {{ .Values.app.deployment.backend.image}}:pink
      priorityClassName: high