apiVersion: v1
kind: LimitRange
metadata:
  name: simple-limit-range
  namespace: {{ .Values.app.namespace }}
spec:
  limits:
  - default: # this section defines default limits
      memory: 300Mi
    defaultRequest: # this section defines default requests
      memory: 100Mi
    max: # max and min define the limit range
      memory: 700Mi
    min:
      memory: 100Mi
    type: Container