---
apiVersion: batch/v1
kind: Job
metadata:
  name: simple-job
  namespace: {{ .Values.app.namespace }}
spec:
  completions: 5
  parallelism: 10
  backoffLimit: 20
  maxFailedIndexes: 50
  template:
    metadata:
    spec:
      containers:
      - image: vimalsmenon/shell-script
        name: simple-job
      restartPolicy: Never
