apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: simple-hpa
  namespace: {{ .Values.app.namespace }}
spec:
  minReplicas: 2
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: orange-deploy
  metrics:
  - type: Resource
    resource:
      name: memory
      # target:
      #   type: Utilization
      #   averageUtilization: 90
      target:
        type: AverageValue
        averageValue: 100Mi 
