apiVersion: v1
kind: Pod
metadata:
  labels:
    run: app-backend
  name: app-backend
spec:
  containers:
  - image: vimalsmenon/app-backend:brown
    name: app-backend
    imagePullPolicy: Always
    ports:
    - containerPort: 4000
    env:
      - name: NODE_NAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName

# kubectl port-forward app-backend 4000:4000
