---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
  namespace: {{ .Values.app.namespace }}
spec:
  containers:
  - name: alpine
    image: alpine:3.18
    command: ["sleep", "1000000"]
  dnsPolicy: ClusterFirst
  restartPolicy: Always