apiVersion: v1
kind: Service
metadata:
  labels:
    app: simple-deploy
    app.kubernetes.io/managed-by: Helm
  name: simple-deploy
  namespace: {{ .Values.app.namespace }}
spec:
  type: NodePort
  ports:
  - port: 4000
    protocol: TCP
    targetPort: 4000
    nodePort: 30000
  selector:
    app: simple-deploy
status:
  loadBalancer: {}
