apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: simple-deploy
  name: simple-deploy
  namespace: {{ .Values.app.namespace }}
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: simple-deploy
  template:
    metadata:
      labels:
        app: simple-deploy
    spec:
      containers:
      - image: {{ .Values.app.deployment.backend.image }}:pink
        name: app-api
