apiVersion: v1
kind: Service
metadata:
  labels:
    app: simple-service
  name: simple-service
  namespace: {{ .Values.app.namespace }}
spec:
  ports:
  - name: 4000-5000
    port: 5000
    protocol: TCP
    targetPort: 4000
  selector:
    app: simple-pod
  type: ClusterIP
