apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-generic-role-binding
  namespace: {{ .Values.app.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: generic-role
subjects:
- name: local-service-account
  kind: ServiceAccount
