---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: simple-pvc
  namespace: {{ .Values.app.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
