---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple
  namespace: local
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: app.com
    http:
      paths:
      - backend:
          service:
            name: simple-service
            port:
              number: 4000
        path: /
        # pathType: ImplementationSpecific
        pathType: Prefix
      - backend:
          service:
            name: simple-service
            port:
              number: 4000
        path: /testing
        pathType: ImplementationSpecific
