---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: simple-service
  name: simple-service
  namespace: local
spec:
  ports:
  - name: 4000-4000
    port: 4000
    protocol: TCP
    targetPort: 4000
  selector:
    app: simple-pod
  type: ClusterIP
