---
apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.app.backend.name }}
spec:
  containers:
    - name: app-pod
      image: {{ .Values.app.backend.image }}:{{ .Values.app.backend.tag }}
      ports:
        - containerPort: {{ .Values.app.backend.port }}