apiVersion: v1
kind: LimitRange
metadata:
  name: resource-limits
  namespace: {{ .Values.app.namespace }}
spec:
  limits:
  - default: # this section defines default limits
      memory: 512Mi
    defaultRequest: # this section defines default requests
      memory: 120Mi
    max: # max and min define the limit range
      memory: 512Mi
    min:
      memory: 100Mi
    type: Container
