apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: po
  name: simple-pod
  namespace: {{ .Values.app.namespace }}
spec:
  containers:
  - name: {{ .Values.app.deployment.backend.name}}
    image: {{ .Values.app.deployment.backend.image}}:pink
    env:
    - name: STRESS_TIME
      value: "500000"
    resources:
      requests:
        memory: 500Mi
      # limits:
      #   cpu: "0.5"
      #   memory: "400Mi"
