apiVersion: v1
kind: Service
metadata:
  labels:
    app: orange-deploy
    app.kubernetes.io/managed-by: Helm
  name: app-api-service
  namespace: {{ .Values.app.namespace }}
spec:
  ports:
  - port: 4000
    protocol: TCP
    targetPort: 4000
  selector:
    app: app-api-deployment
status:
  loadBalancer: {}
