env: dev
app:
  namespace: local
  service:
    type: ClusterIp

  deployment:
    name: app-api
    replicas: 3
    labels:
      app: api
      tire: backend
    backend:
      name: app-api
      image: vimalsmenon/app-backend
      tag: yellow
      port: 4000