---
apiVersion: v1
kind: Service
metadata:
  name: service-app-api
  namespace: {{ .Values.app.namespace }}
spec:
  selector:
    name: pod-test
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
