apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim-1g
  namespace: {{ .Values.app.namespace }}
spec:
  storageClassName: simple-5gi-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
    limits:
        storage: 1.2Gi
