apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  name: app-ingress
  namespace: {{ .Values.app.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: app.com
    http:
      paths:
      - backend:
          service:
            name: app-api-service
            port:
              number: 4000
        path: /?(.*)
        pathType: Prefix

