apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: alpine-pod
  name: alpine-pod
  namespace: {{ .Values.app.namespace }}
spec:
  containers:
  - name: {{ .Values.app.deployment.backend.name}}
    image: {{ .Values.app.deployment.backend.image}}:network
    imagePullPolicy: Always
    env:
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
