---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: test-network-policy
  namespace: {{ .Values.app.namespace }}
spec:
  podSelector:
    matchLabels:
      run: alpine-pod-01
  policyTypes:
    - Ingress
    - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          run: alpine-pod
    ports:
    - protocol: TCP
      port: 4000
  egress:
  - to:
    - podSelector:
        matchLabels:
          run: alpine-pod-02
    ports:
    - protocol: TCP
      port: 4000
