---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: simple-deploy
    app.kubernetes.io/managed-by: Helm
  name: app-api
  namespace: local
spec:
  selector:
    app: simple-deploy
  type: NodePort
  ports:
  - port: 4000
    protocol: TCP
    targetPort: 4000
    nodePort: 30000

