---
env: dev
app:
  namespace: local
  deployment:
    name: app-api
    replicas: 5
    labels:
      app: api
      tire: backend
    backend:
      name: app-api
      image: vimalsmenon/app-backend
      tag: netpol
      port: 4000
