---
apiVersion: v1
kind: ConfigMap
metadata:
  name: simple-configmap
  namespace: {{ .Values.app.namespace }}
data:
{{- range $key, $value := .Values.app.configMap.data }}
  {{ $key }}: {{ $value }}
{{- end }}
immutable: true
