---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: simple-pod
  name: simple-pod
  namespace: local
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    args: ["sleep 2000"]
    image: alpine
    name: simple-pod
    resources: {}
    env:
    - name: APP_NAME
      value: simple-pod
    - name: APP_TYPE_INTERNAL
      valueFrom:
        configMapKeyRef:
          name: simple-configmap
          key: APP_TYPE
    envFrom:
    - configMapRef:
        name: simple-configmap
    volumeMounts:
    - name: empty-dir
      mountPath: /logs/empty-dir
    - name: hostpath
      mountPath: /logs/hostpath
  volumes:
  - name: empty-dir
    emptyDir: {}
  - name: hostpath
    hostPath:
      path: "/users/volumesHostPath"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
