apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: simple-deploy-04
  name: simple-deploy-04
  namespace: {{ .Values.app.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-pod-04
  strategy: {}
  template:
    metadata:
      labels:
        app: simple-pod-04
    spec:
      containers:
      - image: {{ .Values.app.deployment.backend.image}}:{{ .Values.app.deployment.backend.tag}}
        name: {{ .Values.app.deployment.backend.name }}
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: APP_API
          value: simple-svc-01
        - name: APP_NAME
          value: simple-svc-04