apiVersion: v1
kind: Service
metadata:
  labels:
    app: simple-svc-04
  name: simple-svc-04
  namespace: {{ .Values.app.namespace }}
spec:
  ports:
  - name: 4000-4000
    port: 4000
    protocol: TCP
    targetPort: 4000
  selector:
    app: simple-pod-04
  type: ClusterIP
