apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-ingress
  namespace: {{ .Values.app.namespace }}
  annotations:
    # nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: app.com
    http:
      paths:
      - backend:
          service:
            name: simple-fe-svc
            port:
              number: 3000
        path: /
        pathType: Prefix
  - host: api.app.com
    http:
      paths:
      - backend:
          service:
            name: simple-svc-01
            port:
              number: 4000
        path: /service01/?(.*)
        pathType: ImplementationSpecific
      - backend:
          service:
            name: simple-svc-02
            port:
              number: 4000
        path: /service02/?(.*)
        pathType: ImplementationSpecific
      - backend:
          service:
            name: simple-svc-03
            port:
              number: 4000
        path: /service03/?(.*)
        pathType: ImplementationSpecific
      - backend:
          service:
            name: simple-svc-04
            port:
              number: 4000
        path: /service04/?(.*)
        pathType: ImplementationSpecific
