apiVersion: v1
kind: Service
metadata: 
  labels:
    app: simple-fe-svc
  name: simple-fe-svc
  namespace: {{ .Values.app.namespace }}
spec:
  ports:
  - name: 3000-3000
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: simple-fe-pod
  type: ClusterIP
