---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: simple-5gi-pv
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: simple-5gi-pv
  capacity:
    storage: 5Gi
  hostPath:
    path: /Users/vimalmenon/volumes
