---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: simple-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: hostpath
  hostPath:
    path: /Users/vimalmenon
