---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: simple-local-pvc
  namespace: {{ .Values.app.namespace }}
spec:
  storageClassName: local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
