---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: simple-pod
  name: simple-pod
  namespace: {{ .Values.app.namespace }}
spec:
  containers:
  - image: alpine
    name: simple-pod
    args:
    - "sleep"
    - "50000"
    volumeMounts:
    - name: simple-pvc
      mountPath: "/logs/pvc"
    - name: simple-emptydir
      mountPath: "/logs/emptydir"
    - name: simple-hostpath
      mountPath: "/logs/hostpath"
    - name: simple-local-pvc
      mountPath: "/logs/local"
  nodeName: local-m02
  volumes:
  - name: simple-pvc
    persistentVolumeClaim:
      claimName: simple-pvc
  - name: simple-local-pvc
    persistentVolumeClaim:
      claimName: simple-local-pvc
  - name: simple-emptydir
    emptyDir: {}
  - name: simple-hostpath
    hostPath:
      path: "/users/volumesHostPath"

