apiVersion: v1
kind: Pod
metadata:
  labels:
    app: simple-pod
  name: simple-pod
  namespace: {{ .Values.app.namespace }}
spec:
  containers:
  - image: nginx
    name: {{ .Values.app.deployment.name }}
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: app
            operator: NotIn
            values:
            - special