---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: simple-pod-with-node-name
  name: simple-pod-with-node-name
  namespace: {{ .Values.app.namespace }}
spec:
  containers:
  - image: nginx
    name: {{ .Values.app.deployment.name }}
  nodeName: local
