env: dev
app:
  namespace: local
  service:
    type: ClusterIp
  configMap :
    name: simple-config
    data:
      app: "app-api"
      appVersion: "0.0.0"
      testing: "testing"
  deployment:
    name: app-api
    replicas: 6
    labels:
      app: api
      tire: backend
    backend:
      name: app-api
      image: vimalsmenon/app-backend
      tag: logs
      port: 4000
