apiVersion: v1
kind: Service
metadata:
  labels:
    app: first-deploy
    app.kubernetes.io/managed-by: Helm
    env: local
    type: blue
  name: first-deploy
  namespace: local
spec:
  ports:
  - port: 4000
    protocol: TCP
    targetPort: 4000
  selector:
    app: first-deploy
    env: {{ .Values.env }}
    type: blue
  type: {{ .Values.app.service.type }}
