apiVersion: v1
kind: Service
metadata:
  labels:
    app: simple-deploy
    app.kubernetes.io/managed-by: Helm
    env: local
  name: simple-deploy
  namespace: {{ .Values.app.namespace }}
spec:
  ports:
  - port: 4000
    protocol: TCP
    targetPort: 4000
    nodePort: {{ .Values.app.service.nodePort }}
  selector:
    app: simple-deploy
    env: {{ .Values.env }}
  type: {{ .Values.app.service.type }}
